---
# NOTE: this file is managed by terraform
# https://devtodevops.com/hadolint-dockerfile/

failure-threshold: info  # error, warning, info, style, ignore, none
format: tty  # tty, json, checkstyle, codeclimate, gitlab_codeclimate, gnu, codacy, sonarqube, sarif
no-color: true
no-fail: false
strict-labels: true
verbose: false
ignored:
