---
# NOTE: this file is managed by terraform
# ref: https://github.com/marketplace/actions/yaml-lint

extends: default

ignore: |
  tests/

rules:
  line-length:
    max: 125
    level: warning

  indentation: disable
