---

name: re-dependency-review

on:  # yamllint disable-line rule:truthy
  workflow_call:

permissions:
  contents: read

jobs:
  review: # https://github.com/actions/dependency-review-action
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Pull Request Dependency Review
      uses: actions/dependency-review-action@595b5aeba73380359d98a5e087f648dbb0edce1b # 4.7.3
      with:
        license-check: false
        vulnerability-check: true
        show-openssf-scorecard: false
        fail-on-severity: low
