---

name: re-pre-commit

on:  # yamllint disable-line rule:truthy
  workflow_call:

  workflow_dispatch:

env:
  HADOLINT_VERSION: 'v2.12.0'
  PYTHON_VERSION: '3.12.x'
  TERRAFORM_VERSION: '1.11.x'

permissions:
  contents: read

jobs:
  default-run:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - shell: bash
      run: |
        # install package
        make test-install

    - shell: bash
      run: |
        # Pyscan vulnerabilities on python dependencies
        [[ ! -f "requirements.txt" && ! -f "pyproject.toml" ]] || pyscan -d .

    - shell: bash
      run: |
        # install hadolint from binary
        wget -O hadolint https://github.com/hadolint/hadolint/releases/download/${{ env.HADOLINT_VERSION }}/hadolint-Linux-x86_64
        chmod +x hadolint
        sudo mv hadolint /usr/bin/
        hadolint --version

    - name: Install terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Install tflint
      uses: terraform-linters/setup-tflint@ae78205cfffec9e8d93fd2b3115c7e9d3166d4b6 # v5.0.0

    - name: Run pre-commit on everything
      run: pre-commit run -a -v

  add-on-checkov:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Run Checkov Github Action
      id: checkov
      uses: bridgecrewio/checkov-action@eec884fd62682f5f2b33e303e160d5e2fe8d89ec # v12.3052.0
      with:
        log_level: WARNING
        quiet: false
        skip_results_upload: "true"
        enable_secrets_scan_all_files: "true"
        skip_check: CKV_GIT_1,CKV_GIT_3,CKV_GIT_5,CKV_GIT_6,CKV2_GIT_1,CKV2_GHA_1,CKV_DOCKER_2,CKV_DOCKER_3
        # Skip Check Details
        # ID           Description
        # CKV_GIT_1    - Ensure GitHub repository is Private
        # CKV_GIT_3    - Ensure GitHub Repository defined in Terraform have vulnerability alerts enabled
        # CKV_GIT_5    - Ensure GitHub pull requests should require at least 2 approvals
        # CKV_GIT_6    - Ensure GitHub branch protection rules requires signed commits
        # CKV2_GIT_1   - Ensure each Repository has branch protection associated
        # CKV2_GHA_1   - Ensure top-level permissions are not set to write-all
        # CKV_DOCKER_2 - Ensure that HEALTHCHECK instructions have been added to container images
        # CKV_DOCKER_3 - Ensure that a user for the container has been created
